CREATE SEQUENCE SEQ_BAIRRO
  START WITH 1
  INCREMENT BY 1
  NOCACHE
  NOCYCLE;

CREATE TABLE TBL_BAIRRO (
    ID_BAIRRO INTEGER DEFAULT SEQ_BAIRRO.NEXTVAL NOT NULL,
    NOME_BAIRRO VARCHAR2(100) NOT NULL,
    NOME_CIDADE VARCHAR2(100) NOT NULL,
    NUMERO_CEP VARCHAR2(20) NOT NULL
);