CREATE SEQUENCE SEQ_CALENDARIO
  START WITH 1
  INCREMENT BY 1
  NOCACHE
  NOCYCLE;

CREATE TABLE TBL_CALENDARIO_COLETA (
    ID_CALENDARIO INTEGER DEFAULT SEQ_CALENDARIO.NEXTVAL NOT NULL,
    NOME_DIA_COLETA VARCHAR2(50) NOT NULL,
    HORA_COLETA VARCHAR2(10) NOT NULL
);