name: CI/CD para Gestão de Resíduos

on:
  push:
    branches:
      - main
      - staging

env:
  AZURE_CONTAINER_REGISTRY: gestaoResiduos.azurecr.io
  IMAGE_NAME: gestao_residuos
  RESOURCE_GROUP: FIAP
  WEBAPP_NAME: gestao-residuos

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do Código
        uses: actions/checkout@v3

      - name: Configurar Java
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Build do Projeto com Maven
        run: |
          mvn clean install -DskipTests=true  # Pule testes para agilizar o processo

  dockerize:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout do Código
        uses: actions/checkout@v3

      - name: Build da Imagem Docker
        run: |
          docker build -t $AZURE_CONTAINER_REGISTRY/$IMAGE_NAME:latest .

      - name: Push da Imagem para o ACR
        run: |
          echo "${{ secrets.AZURE_CREDENTIALS }}" | docker login $AZURE_CONTAINER_REGISTRY --username ${{ secrets.AZURE_USERNAME }} --password-stdin
          docker push $AZURE_CONTAINER_REGISTRY/$IMAGE_NAME:latest

  deploy-staging:
    runs-on: ubuntu-latest
    needs: dockerize
    if: github.ref == 'refs/heads/staging'

    steps:
      - name: Deploy em Staging
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.WEBAPP_NAME }}-staging
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}  # Referência ao Publish Profile
          images: $AZURE_CONTAINER_REGISTRY/$IMAGE_NAME:latest

  deploy-production:
    runs-on: ubuntu-latest
    needs: dockerize
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Deploy em Produção
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.WEBAPP_NAME }}  # Nome do Azure Web App
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}  # Referência ao Publish Profile
          images: $AZURE_CONTAINER_REGISTRY/$IMAGE_NAME:latest
